id = "nvidia-cuda-rhel9-x86_64"
name = "NVIDIA repos"
type = "yum-baseurl"
url = "https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64"
check_gpg = false
check_ssl = false
system = false
gpgkeys = ["https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub"]
