id = "rhocp-4.16-rc"
name = "Red Hat OpenShift Container Platform 4.14 for RHEL 9"
type = "yum-baseurl"
url = "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp/latest-4.16/el9/os"
check_gpg = false
check_ssl = false
system = false
rhsm = true
